# Generated by Django 5.2.13 on 2026-04-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_files/%Y/%m/%d/', verbose_name='Excel файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='publisher.document')),
            ],
            options={
                'verbose_name': 'Сессия загрузки',
                'verbose_name_plural': 'Сессии загрузки',
            },
        ),
        migrations.CreateModel(
            name='PublicationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.CharField(max_length=64, verbose_name='Номер профиля')),
                ('social_network', models.CharField(max_length=32, verbose_name='Соцсеть')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('title', models.CharField(max_length=255, verbose_name='Название видео')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('publish_time', models.DateTimeField(verbose_name='Время публикации')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('downloading', 'Скачивается видео'), ('sending', 'Отправляется в Geelark'), ('success', 'Успешно'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='publisher.uploadsession')),
            ],
            options={
                'verbose_name': 'Задача на публикацию',
                'verbose_name_plural': 'Задачи на публикацию',
            },
        ),
    ]
